StudentTracking/Models/ErrorViewModel.cs
using System;

namespace StudentTracking.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentTracking/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StudentTracking.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StudentTracking.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentTracking/Controllers/StudentBookController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudentTracking.BusinessLayer.Concrete;
using StudentTracking.BusinessLayer.ValidationRules.FluentValidation;
using StudentTracking.DataAccessLayer.Concrete.Repository;
using StudentTracking.DataAccessLayer.EntityFramework;
using StudentTracking.EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentTracking.PresentationLayer.Controllers
{
    public class StudentBookController : Controller
    {
        BookManager bookmanager = new BookManager(new EfBookDal());
        LessonManager lessonManager = new LessonManager(new EfLessonDal());

        BookValidation bookValidation = new BookValidation();
        ValidationResult result;
        public IActionResult Index()
        {
            var books = bookmanager.List();
            return View(books);
        }

        public IActionResult Create()
        {
            List<SelectListItem> valueBook = (from lesson in lessonManager.List()
                                                  select new SelectListItem
                                                  {
                                                      Text = lesson.LessonName,
                                                      Value = lesson.LessonId.ToString(),
                                                  }).ToList();
            ViewBag.valueBook = valueBook;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book book)
        {
            List<SelectListItem> valueBook = (from lesson in lessonManager.List()
                                              select new SelectListItem
                                              {
                                                  Text = lesson.LessonName,
                                                  Value = lesson.LessonId.ToString(),
                                              }).ToList();
            ViewBag.valueBook = valueBook;

            result = bookValidation.Validate(book);
            if (result.IsValid)
            {
                bookmanager.Add(book);
                return RedirectToAction("Index");

            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View(book);
        }

        public IActionResult Edit(int id)
        {
            List<SelectListItem> valueBook = (from lesson in lessonManager.List()
                                              select new SelectListItem
                                              {
                                                  Text = lesson.LessonName,
                                                  Value = lesson.LessonId.ToString(),
                                              }).ToList();
            ViewBag.valueBook = valueBook;

            var book = bookmanager.GetById(id);
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Book book)
        {
            List<SelectListItem> valueBook = (from lesson in lessonManager.List()
                                              select new SelectListItem
                                              {
                                                  Text = lesson.LessonName,
                                                  Value = lesson.LessonId.ToString(),
                                              }).ToList();
            ViewBag.valueBook = valueBook;
            result = bookValidation.Validate(book);
            if (result.IsValid)
            {
                bookmanager.Update(book);
                return RedirectToAction("Index");

            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View(book);
        }

        public IActionResult Delete(int id)
        {
            var book = bookmanager.GetById(id);
            bookmanager.Delete(book);
            return RedirectToAction("Index");
        }
    }
}

StudentTracking/Controllers/StudentExamController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using StudentTracking.BusinessLayer.Concrete;
using StudentTracking.BusinessLayer.ValidationRules.FluentValidation;
using StudentTracking.DataAccessLayer.EntityFramework;
using StudentTracking.EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentTracking.PresentationLayer.Controllers
{
    public class StudentExamController : Controller
    {
        ExamTYTManager examManager = new ExamTYTManager(new EfExamTYTDal());
        ExamTYTValidation examTYTValidation = new ExamTYTValidation();
        ValidationResult result;

        public IActionResult Index()
        {
            var exames = examManager.List();
            return View(exames);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(ExamTYT examTYT)
        {
            result = examTYTValidation.Validate(examTYT);
            if (result.IsValid)
            {

                examManager.Add(examTYT);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View(examTYT);
        }

        public IActionResult Edit(int id)
        {
            var exam = examManager.GetById(id);
            return View(exam);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(ExamTYT examTYT)
        {
            result = examTYTValidation.Validate(examTYT);
            if (result.IsValid)
            {

                examManager.Update(examTYT);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View(examTYT);
        }

        public IActionResult Delete(int id)
        {
            var exam = examManager.GetById(id);
            if (exam != null)
            {
                examManager.Delete(exam);
            }
            else
            {
                ViewBag.alerttt = "Böyle bir sınav bulunamadı";
            }
            return RedirectToAction("Index");
        }
    }
}

StudentTracking/Views/Home/Index.cshtml
@{
    Layout = "_StudentLayout";
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StudentTracking/Views/StudentBook/Create.cshtml
@model StudentTracking.EntityLayer.Book
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<head>

    <link href="~/css/BookAdded/BookRegister.css" rel="stylesheet" />
</head>

<div class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="~/img/kitap.png" />
            <h3>KİTAP EKLE</h3>
        </div>
        <div class="col-md-9 register-right">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="register-heading">Yeni bir kitap ekle!</h3>
                    <div class="row register-form">
                        <div class="col-md-12">
                            @using (Html.BeginForm("Create", "StudentBook", FormMethod.Post))
                            {@Html.AntiForgeryToken()
                                <div class="form-group">
                                    @Html.Label("Kitap Adı")
                                    @Html.TextBoxFor(c => c.BookName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(b => b.BookName, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.Label("Kitap Sayfa")
                                    @Html.TextBoxFor(c => c.BookPageCount, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(b => b.BookPageCount, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.Label("Ders")
                                    @Html.DropDownListFor(b => b.LessonId, (List<SelectListItem>)ViewBag.valueBook, "Ders seçiniz", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(b=>b.LessonId, "", new { @class = "text-danger" })
                                </div>
                                <div class="text-center">
                                    <button class="btn btn-primary" type="submit">Kaydet</button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StudentTracking/Views/StudentBook/Edit.cshtml
@model StudentTracking.EntityLayer.Book
@{
    ViewData["Title"] = "Kitap Güncelle";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<head>

    <link href="~/css/BookAdded/BookRegister.css" rel="stylesheet" />
</head>

<div class="container register">
    <div class="row">
        <div class="col-md-3 register-left" style="margin-top:10rem;">
            <img src="~/img/kitap.png" />
            <h3>KİTAP GÜNCELLE</h3>
        </div>
        <div class="col-md-9 register-right">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="register-heading">Durumunu Güncelle!</h3>
                    <div class="row register-form">
                        <div class="col-md-12">
                            @using (Html.BeginForm("Edit", "StudentBook", FormMethod.Post))
                            {@Html.AntiForgeryToken()
                                @Html.HiddenFor(b=>b.BookId)
                            <div class="form-group">
                                @Html.Label("Kitap Adı")
                                @Html.TextBoxFor(c => c.BookName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.BookName, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.Label("Kitap Sayfa Sayısı")
                                @Html.TextBoxFor(c => c.BookPageCount, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.BookPageCount, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.Label("Çözülen Sayfa Sayısı")
                                @Html.TextBoxFor(c => c.Revalsed, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.Revalsed, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.Label("Ders")
                                @Html.DropDownListFor(b => b.LessonId, (List<SelectListItem>)ViewBag.valueBook, "Ders seçiniz", new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.LessonId, "", new { @class = "text-danger" })
                            </div>
                            <div class="text-center">
                                <button class="btn btn-primary" type="submit">Güncelle</button>
                            </div>
                        }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StudentTracking/Views/StudentExam/Create.cshtml
@model StudentTracking.EntityLayer.ExamTYT
@{
    ViewData["Title"] = "Yeni Sınav Ekle";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

@using (Html.BeginForm("Create", "StudentExam", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container col-md-11 justify-content-center px-5 pb-5 pt-2 form-group border border-primary" style="margin-top:2%;">
        <div class="row justify-content-between my-3 border border-primary p-3">
            <h2 class="text-primary font-weight-bold">Yeni Sınav Ekle</h2>
            <div class="text-center">
                <button type="submit" class="btn  btn-lg btn-primary">
                    Kaydet
                </button>
            </div>
        </div>
        <div class="row border border-primary p-3">
            <div class="col-md-3">
                @Html.Label("Sınav Tarihi")
                <input type="date" name="ExamTYTDate" class="form-control">
                @Html.ValidationMessageFor(w => w.ExamTYTDate, null, new { @class = "text-danger" })
            </div>
            <div class="col-sm-9">
                @Html.Label("Sınav Adı")
                @Html.TextBoxFor(w => w.ExamTYTName, new { @class = "form-control" })
                @Html.ValidationMessageFor(w => w.ExamTYTName, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="row border border-primary mt-3 p-3">
            <h3 class="my-2 text-primary font-weight-bold">Dersler</h3>

            <div class="row mt-3 text-right">
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-5 pl-5">Türkçe</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.TurkceDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.TurkceDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.TurkceYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.TurkceYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-3">Sosyal Bilimler</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(w => w.SosyalBilimlerDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.SosyalBilimlerDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.SosyalBilimlerYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.SosyalBilimlerYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>




            </div>
            <div class="row mt-3 text-right">
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-5">Matematik</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.MatematikDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.MatematikDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.MatematikYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.MatematikYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-5">Fen  Bilimler</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.FenBilimleriDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.FenBilimleriDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.FenBilimleriYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.FenBilimleriYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

       
    </div>
}

StudentTracking/Views/StudentExam/Edit.cshtml
@model StudentTracking.EntityLayer.ExamTYT
@{
    ViewData["Title"] = "Sınav Güncelle";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}


@using (Html.BeginForm("Edit", "StudentExam", FormMethod.Post))
{
    @Html.HiddenFor(e=>e.ExamTYTId)
    @Html.AntiForgeryToken()
    <div class="container col-md-11 justify-content-center px-5 pb-5 pt-2 form-group border border-primary" style="margin-top:2%;">
        <div class="row justify-content-between my-3 border border-primary p-3">
            <h2 class="text-primary font-weight-bold">Sınav Güncelle</h2>
            <div class="text-center">
                <button type="submit" class="btn  btn-lg btn-success">
                    Güncelle
                </button>
            </div>
        </div>
        <div class="row border border-primary p-3">
            <div class="col-md-3">
                @Html.Label("Sınav Tarihi")
                <input asp-for="ExamTYTDate" type="date" name="ExamTYTDate" class="form-control">
                @Html.ValidationMessageFor(w => w.ExamTYTDate, null, new { @class = "text-danger" })
            </div>
            <div class="col-sm-9">
                @Html.Label("Sınav Adı")
                @Html.TextBoxFor(w => w.ExamTYTName, new { @class = "form-control" })
                @Html.ValidationMessageFor(w => w.ExamTYTName, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="row border border-primary mt-3 p-3">
            <h3 class="my-2 text-primary font-weight-bold">Dersler</h3>

            <div class="row mt-3 text-right">
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-5 pl-5">Türkçe</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.TurkceDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.TurkceDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.TurkceYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.TurkceYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-3">Sosyal Bilimler</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(w => w.SosyalBilimlerDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.SosyalBilimlerDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.SosyalBilimlerYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.SosyalBilimlerYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>




            </div>
            <div class="row mt-3 text-right">
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-5">Matematik</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.MatematikDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.MatematikDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.MatematikYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.MatematikYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row align-items-center">
                        <h4 class="text-danger font-weight-bold ml-5">Fen  Bilimler</h4>
                        <div class="col mr-5 pr-5">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Doğru")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.FenBilimleriDogru, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.FenBilimleriDogru, null, new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="row">
                                    <div class="col-md">
                                        @Html.Label("Yanlış")
                                    </div>
                                    <div class="col-md">
                                        @Html.TextBoxFor(w => w.FenBilimleriYanlis, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(w => w.FenBilimleriYanlis, null, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}